tabs: [Arms, Legs, Other]

order : [Left, Right, Torso, Head]

Arms: 
    Left [deg]:  [[l_arm_sh_p1, l_arm_sh_r, l_arm_sh_p2], [l_arm_el_y], [l_arm_wr_r, l_arm_wr_y, l_arm_wr_p]]
    Right [deg]: [[r_arm_sh_p1, r_arm_sh_r, r_arm_sh_p2], [r_arm_el_y], [r_arm_wr_r, r_arm_wr_y, r_arm_wr_p]]
    
Legs:
    Left [deg]:  [[l_leg_hip_y, l_leg_hip_r, l_leg_hip_p], [l_leg_kn_p], [l_leg_an_p, l_leg_an_r]]
    Right [deg]: [[r_leg_hip_y, r_leg_hip_r, r_leg_hip_p], [r_leg_kn_p], [r_leg_an_p, r_leg_an_r]]
    
Other:
    Head [deg]:  [[head_y, head_p]]
    Torso [deg]: [[torso_y]]

