# paths the wizard pages can take

# intro page and summary page don't have to be specified

# 'show' specifies what parts of the robot should remain visible
# in a rviz preview of which joints are going to be calibrated on each path
# e.g. 'arm' will show all links with arm in the name, '' will show every link

full calibration:
    path: ['Pose', 'Left Hip', 'Right Hip', 'Knees', 'Left Ankle', 'Right Ankle', 'Torso',
     'Head', 'Left Shoulder', 'Left Elbow', 'Left Wrist', 'Right Shoulder', 'Right Elbow',
     'Walking Calibration', 'Right Wrist']
    show: ''
    
arm calibration:
    path: ['Pose', 'Left Shoulder', 'Left Elbow', 'Left Wrist', 'Right Shoulder', 'Right Elbow', 'Right Wrist']
    show: 'arm'
    
leg calibration:
    path: ['Pose', 'Left Hip', 'Right Hip', 'Knees', 'Left Ankle', 'Right Ankle']
    show: 'leg'

leg parallelism:
    path: ['Pose', 'Hips Yaw', 'Hips Pitch', 'Knees Pitch', 'Ankles Pitch']
    show: 'leg'
    
walking calibration:
    path: ['Walking Calibration']
    show: 'leg_an_r'
    
# generates one of each page type
debug:
    path: ['Pose', 'Left Hip', 'Knees', 'Walking Calibration']
    show: ''
    
