joints:
  groups:
    finger:
#     prefix: Loaded by launchfile
      name: "Fingers"
  
    head:
      prefix: [head]
      name: "Head"
  
    right_arm:
      prefix: [r_arm]
      name: "Right Arm"
  
    left_arm:
       prefix: [l_arm]
       name: "Left Arm"
   
    right_leg:
      prefix: [r_leg]
      name: "Right Leg"
   
    left_leg:
      prefix: [l_leg]
      name: "Left Leg"

    torso:
      prefix: [torso]
      name: "Torso"
