#!/usr/bin/env python

import sys

pkg = 'thor_mang_torque_control'
widget = 'torque_control_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))
