#!/usr/bin/env python

import sys

pkg = 'thor_mang_supervisor'
widget = 'lidar_control_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))

