#!/usr/bin/env python

import rospy
import signal
import math
import xml.dom.minidom

from threading import Thread

from std_msgs.msg import Bool
from sensor_msgs.msg import JointState
from thor_mang_calibration.msg import Joints

class JointStatePublisher:
    def __init__(self):
        robot_description = rospy.get_param('robot_description')
        self._robot = xml.dom.minidom.parseString(robot_description).getElementsByTagName('robot')[0]
        self._joint_names = self._get_joints_from_robot()
        
        self._turning_speed = math.radians(2)
        self._turning_range = math.radians(20)
        
        self._preview_pose = {}
        self._show_turning_direction = False
        self._turning_joints = []
        self._turning_joints_old_position = {}
        
        self._joint_state_message = JointState()
        self._joint_state_message.name = self._joint_names
        self._joint_state_message.position.extend([0] * len(self._joint_names))
        #self._joint_state_message.velocity.extend([0] * len(self._joint_names))
        
        self.preview_pose_sub = rospy.Subscriber("preview_pose", JointState, self._receive_preview_pose)
        self.show_turning_dir_pub = rospy.Subscriber("show_joint_turning_direction", Bool, self._receive_show_turning_dir) 
        self.turning_joints_pub = rospy.Subscriber("turning_joints", Joints, self._receive_turning_joints)
        
        self.publisher = rospy.Publisher('joint_states', JointState, queue_size = 10)
        
    def _receive_preview_pose(self, data):
        for i in range(0, len(data.name)):
            self._preview_pose[data.name[i]] = data.position[i]
            
    def _receive_show_turning_dir(self, data):
        self._show_turning_direction = data.data
        
    def _receive_turning_joints(self, data):
        self._turning_joints = data.joints
        for joint in self._turning_joints:
            self._turning_joints_old_position[joint] = self._preview_pose[joint]
        
    def _get_joints_from_robot(self):
        joint_names = []
        
        for child in self._robot.childNodes:
            if child.localName == 'joint':
                if not child.getAttribute('type') in ['fixed', 'floating', 'planar']:
                    joint_names.append(child.getAttribute('name'))
                
        return joint_names
        
    def _preview_pose_to_position(self):
        for i in range(0, len(self._joint_state_message.name)):
            name = self._joint_state_message.name[i]
            if name in self._preview_pose.keys():
                self._joint_state_message.position[i] = self._preview_pose[name]
        
    def _turn_joints(self):
        for i in range(0, len(self._joint_state_message.name)):
            name = self._joint_state_message.name[i]
            if name in self._turning_joints:
                current_position = self._joint_state_message.position[i] 
                self._joint_state_message.position[i] = self._calculate_new_position(name, i)
                self._turning_joints_old_position[name] = current_position
        
    def _calculate_new_position(self, joint, i):
        max_val = self._preview_pose[joint] + self._turning_range / 2.0
        min_val = self._preview_pose[joint] - self._turning_range / 2.0
        
        new_val = self._turning_joints_old_position[joint] + self._turning_speed
        
        if new_val >= max_val:
            new_val = min_val
            
        return new_val
        
    def loop(self):
        hz = 10
        r = rospy.Rate(hz)
        while not rospy.is_shutdown():
            self._joint_state_message.header.stamp = rospy.Time.now()
            
            # do other stuff here
            if self._show_turning_direction:
                self._turn_joints()
            else:
                self._preview_pose_to_position()
            
            self.publisher.publish(self._joint_state_message)
            r.sleep()
             

        
if __name__ == '__main__':
    try:
        rospy.init_node('joint_state_publisher')
        jsp = JointStatePublisher()

        Thread(target=jsp.loop).start()
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        
    except Exception as e:
        print('Error in joint_state_publisher: ' + str(e))
pass
