#!/usr/bin/env python

import sys

pkg = 'thor_mang_com_adjustment'
widget = 'com_adjustment_widget'

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg+'.'+widget))

